#!/usr/bin/env python

# ----------------------------------------------------------------------
# SSLCAUDIT - a tool for automating security audit of SSL clients
# Released under terms of GPLv3, see COPYING.TXT
# Copyright (C) 2012 Alexandre Bezroutchko abb@gremwell.com
# ----------------------------------------------------------------------
# Code handling keyboard interrupts contributed by Raf Somers (raf.somers@telenet.be)
# ----------------------------------------------------------------------


import sys, logging
from src.core.ConfigError import ConfigError
from src.core.SSLCAuditCLI import SSLCAuditCLI

def main(argv):
    try:
        main = SSLCAuditCLI(argv[1:])
        main.start()
    except KeyboardInterrupt as ex:
        print 'Got KeyboardInterrupt exception before main loop started, exiting'
        return 1
    except ConfigError as ex:
        print 'Configuration error: %s' % ex
        return 1
    except RuntimeError as ex:
        print 'Runtime error: %s' % ex
        return 1

    # wait for the main thread to finish, handle Ctrl-C if any
    interrupted_by_user = False
    while main.isAlive():
        try:
            main.join(1)
        except KeyboardInterrupt:
            print 'Got KeyboardInterrupt exception, aborting the program ...'
            main.stop() # graceful death
            interrupted_by_user = True
 
    # if the program is aborted by the user, return exitcode 1
    if interrupted_by_user:
        return 1
    else:
        return 0

if __name__ == "__main__":
    logging.basicConfig()
    sys.exit(main(sys.argv))

