#!/usr/bin/env python

# ----------------------------------------------------------------------
# SSLCAUDIT - a tool for automating security audit of SSL clients
# Released under terms of GPLv3, see COPYING.TXT
# Copyright (C) 2012 Alexandre Bezroutchko abb@gremwell.com
# ----------------------------------------------------------------------

import sys, logging
from src.core.SSLCAuditCLI import SSLCAuditCLI

def main(argv):
	isbusy=True
	main = SSLCAuditCLI(argv[1:])
	main.start()
	while isbusy:
		try:
			main.join(1)
			isbusy = main.isAlive()
		except KeyboardInterrupt:
			main.die() #graceful death
			main.join(10)
			isbusy=False
	return 0

if __name__ == "__main__":
	logging.basicConfig()
	sys.exit(main(sys.argv))

