#!/usr/bin/env python

# ----------------------------------------------------------------------
# SSLCAUDIT - a tool for automating security audit of SSL clients
# Released under terms of GPLv3, see COPYING.TXT
# Copyright (C) 2012 Alexandre Bezroutchko abb@gremwell.com
# ----------------------------------------------------------------------

import sys
from src.Main import Main

def main(argv):
	main = Main(argv[1:])
	main.start()
	main.join()
	return 0

if __name__ == "__main__":
	sys.exit(main(sys.argv))

